apiVersion: v1
kind: Service
metadata:
  name: antenna-receiver
  labels:
    app: antenna-receiver
spec:
  selector:
    app: antenna-receiver
  ports:
    - name: port-9043
      port: 9043
      targetPort: 9043
      protocol: TCP
  type: ClusterIP
