---
version: 1.0.0

logging:
  level: info

transmitter:
  server:
    ssl:
      key: 'ks:server/key'
      certificate: 'ks:server/cert'
  base_url: "https://transmitter.dune.com:9044"
  issuer: "https://transmitter.dune.com"
  event_types:
    - "https://schemas.openid.net/secevent/ssf/event-type/verification"
    - "https://schemas.openid.net/secevent/caep/event-type/session-revoked"
    - "https://schemas.openid.net/secevent/caep/event-type/device-compliance-change"
    - "https://iam.ibm.com/secevent/ssf/event-type/application"

  runtime:
    enabled: true
    jwks:
      signing_keystore: jwks_keys
      default_signing_key: jwtsigner
    sign_poll_set: true

  ingester:
    enabled: true
    sources:
      - id: mdm
        type: http_push
        transform_rule:
          type: javascript
          content: "@js/mdm_mapper.js"
      - id: ssf_compliant
        type: http_push
        transform_rule:
          type: javascript
          content: "@js/ssf_mapper.js"

javascript:
  timeout: 10
  max_concurrent_jobs: 16
  max_ctx_pre_isolate: 50

authorization_schemes:
  - spec_urn: "urn:ietf:rfc:6749"
    client_id: "NOT_A_VALID_VALUE"
    client_secret: "NOT_A_VALID_VALUE"
    client_authentication_method: "client_secret_post"
    discovery_uri: "https://tenant.verify.ibm.com/oauth2/.well-known/openid-configuration"
