services:
  antenna-transmitter:
    image: "icr.io/ibm-verify/ibm-verify-antenna-transmitter:26.03.0"
    hostname: ${HOSTNAME}
    container_name: ${HOSTNAME}
    networks:
      - antenna-network
    ports:
      - ${TRANSMITTER_PORT}:9044
    volumes:
      - ./configs:/var/antenna/config
      - ./db:/db
    env_file: "./.env"

networks:
  antenna-network:
    name: antenna-network
    external: true
