apiVersion: v1
kind: Service
metadata:
  name: antenna-postgres
  labels:
    app: antenna-postgres
spec:
  selector:
    app: antenna-postgres
  ports:
    - name: port-5432
      port: 5432
      targetPort: 5432
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: antenna-kafka
  labels:
    app: antenna-kafka
spec:
  selector:
    app: antenna-kafka
  ports:
    - name: port-9092
      port: 9092
      targetPort: 9092
      protocol: TCP
  type: ClusterIP
