CREATE TABLE IF NOT EXISTS SESSION_STORAGE
(
    TENANT_UUID VARCHAR(50)  NOT NULL,
    KEY         VARCHAR(256) NOT NULL,
    VALUE       TEXT         NOT NULL,
    EXP         BIGINT,
    CONSTRAINT PK_SESSION_STORAGE PRIMARY KEY (TENANT_UUID, KEY)
    );

CREATE INDEX IF NOT EXISTS SESSION_STORAGE_IDX ON SESSION_STORAGE (EXP ASC);

CREATE TABLE IF NOT EXISTS RX_STREAM
(
    TENANT_UUID                  VARCHAR(50)   NOT NULL,
    RECEIVER_STREAM_ID           VARCHAR(50)   NOT NULL,
    STREAM_ID                    VARCHAR(50)   NOT NULL,
    ISS                          VARCHAR(2048) NOT NULL,
    AUD                          TEXT          NOT NULL,
    EVENTS_SUPPORTED             TEXT,
    EVENTS_REQUESTED             TEXT          NOT NULL,
    EVENTS_DELIVERED             TEXT          NOT NULL,
    DELIVERY_METHOD              VARCHAR(20)   NOT NULL,
    DELIVERY_ENDPOINT_URL        VARCHAR(2048),
    MIN_VERIFICATION_INTERVAL    INTEGER       NOT NULL,
    DESCRIPTION                  VARCHAR(1024),
    META_DATA_URL                VARCHAR(2048) NOT NULL,
    METADATA_URI_AUTH            BOOLEAN       NOT NULL,
    NAME                         VARCHAR(256)  NOT NULL,
    STATUS                       VARCHAR(10)   NOT NULL,
    STATUS_REASON                VARCHAR(1024),
    TYPE                         VARCHAR(50)   NOT NULL,
    SUBJECT_NORMALIZATION        TEXT          NOT NULL,
    NEXT_POLL_TIME               TIMESTAMP     NOT NULL,
    AUTH_SCHEME                  TEXT          NOT NULL,
    MAX_EVENTS                   INTEGER       NOT NULL,
    POLL_INTERVAL_SEC            INTEGER       NOT NULL,
    RETURN_IMMEDIATELY           BOOLEAN       NOT NULL,
    ROUTING_MODE                 VARCHAR(25),
    ROUTING_EVENT_PROPERTY_NAME  VARCHAR(128),
    CREATED_AT                   TIMESTAMP     NOT NULL,
    UPDATED_AT                   TIMESTAMP,
    CONSTRAINT PK_RX_STREAM PRIMARY KEY (TENANT_UUID, RECEIVER_STREAM_ID),
    CONSTRAINT TID_RSID_SID UNIQUE (TENANT_UUID, RECEIVER_STREAM_ID, STREAM_ID)
    );

CREATE INDEX IF NOT EXISTS RX_STREAM_IDX_TID ON RX_STREAM (TENANT_UUID);
CREATE INDEX IF NOT EXISTS RX_STREAM_IDX_DMSTNPT ON RX_STREAM (DELIVERY_METHOD, STATUS, NEXT_POLL_TIME);

CREATE TABLE IF NOT EXISTS TX_STREAM
(
    TENANT_UUID           VARCHAR(50) NOT NULL,
    STREAM_ID             VARCHAR(50) NOT NULL,
    OWNER_ID              VARCHAR(50) NOT NULL,
    DESCRIPTION           VARCHAR(1024),
    AUDIENCE              TEXT        NOT NULL,
    EVENTS_REQUESTED      TEXT        NOT NULL,
    DELIVERY_METHOD       VARCHAR(20) NOT NULL,
    DELIVERY_ENDPOINT_URL VARCHAR(2048),
    DELIVERY_AUTH_HEADER  TEXT,
    STATUS                VARCHAR(10),
    STATUS_REASON         VARCHAR(1024),
    RECENT_ENABLED        BOOLEAN,
    SIGNING_KEY           VARCHAR(50),
    LAST_ACTIVITY_AT      TIMESTAMP,
    CREATED_AT            TIMESTAMP   NOT NULL,
    UPDATED_AT            TIMESTAMP,
    CONSTRAINT PK_TX_STREAM PRIMARY KEY (TENANT_UUID, STREAM_ID, OWNER_ID)
    );

CREATE INDEX IF NOT EXISTS TX_STREAM_IDX_TIDSID ON TX_STREAM (TENANT_UUID, STREAM_ID);
CREATE INDEX IF NOT EXISTS TX_STREAM_IDX_TIDOID ON TX_STREAM (TENANT_UUID, OWNER_ID);

CREATE TABLE IF NOT EXISTS EVENT_STREAM
(
    TENANT_UUID VARCHAR(50),
    EVENT_TYPE  VARCHAR(1024) NOT NULL,
    STREAM_ID   VARCHAR(50)   NOT NULL,
    CONSTRAINT PK_EVENT_STREAM PRIMARY KEY (TENANT_UUID, EVENT_TYPE, STREAM_ID)
    );

CREATE INDEX IF NOT EXISTS EVENT_STREAM_IDX_TIDSID ON EVENT_STREAM (TENANT_UUID, STREAM_ID);
CREATE INDEX IF NOT EXISTS EVENT_STREAM_IDX_TIDETYP ON EVENT_STREAM (TENANT_UUID, EVENT_TYPE);

CREATE TABLE IF NOT EXISTS SET_EVENT
(
    TENANT_UUID    VARCHAR(50)  NOT NULL,
    ID             VARCHAR(255) NOT NULL,
    STREAM_ID      VARCHAR(255) NOT NULL,
    OWNER_ID       VARCHAR(50)  NOT NULL,
    SET            TEXT,
    FORCE_TRANSMIT BOOLEAN,
    CREATED_AT     TIMESTAMP    NOT NULL,
    CONSTRAINT PK_SET_EVENT PRIMARY KEY (TENANT_UUID, ID, STREAM_ID, OWNER_ID)
    );

CREATE INDEX IF NOT EXISTS SET_EVENT_IDX_TIDSIDOID ON SET_EVENT (TENANT_UUID, STREAM_ID, OWNER_ID);

CREATE TABLE IF NOT EXISTS TX_SUBJECT
(
    TENANT_UUID        VARCHAR(50)  NOT NULL,
    STREAM_ID          VARCHAR(50)  NOT NULL,
    SIGNATURE          VARCHAR(255) NOT NULL,
    SUBJECT_PROPERTIES TEXT         NOT NULL,
    VERIFIED           BOOLEAN,
    ACTION             VARCHAR(20)  NOT NULL,
    CREATED_AT         TIMESTAMP    NOT NULL,
    UPDATED_AT         TIMESTAMP,
    CONSTRAINT PK_TX_SUBJECT PRIMARY KEY (TENANT_UUID, STREAM_ID, SIGNATURE)
    );

CREATE TABLE IF NOT EXISTS HEART_BEAT
(
    UUID              VARCHAR(50) NOT NULL,
    TYPE              VARCHAR(50) NOT NULL,
    HEART_BEAT_EXPIRY TIMESTAMP,
    CONSTRAINT PK_HEART_BEAT PRIMARY KEY (UUID, TYPE)
    );

CREATE INDEX IF NOT EXISTS HEART_BEAT_IDX_TYPEXP ON HEART_BEAT (TYPE, HEART_BEAT_EXPIRY);