CREATE TABLE IF NOT EXISTS SESSION_STORAGE
(
    TENANT_ID         TEXT        NOT NULL,
    KEY               TEXT        NOT NULL,
    HOUR_PARTITION_ID INTEGER     NOT NULL,
    VALUE             TEXT        NOT NULL,
    EXP               TIMESTAMPTZ NOT NULL,
    CONSTRAINT PK_SESSION_STORAGE PRIMARY KEY (TENANT_ID, KEY, HOUR_PARTITION_ID)
    ) PARTITION BY LIST (HOUR_PARTITION_ID);
CREATE TABLE IF NOT EXISTS SESSION_STORAGE_P0 PARTITION OF SESSION_STORAGE FOR VALUES IN (0) WITH (FILLFACTOR=90);
CREATE TABLE IF NOT EXISTS SESSION_STORAGE_P1 PARTITION OF SESSION_STORAGE FOR VALUES IN (1) WITH (FILLFACTOR=90);
CREATE TABLE IF NOT EXISTS SESSION_STORAGE_P2 PARTITION OF SESSION_STORAGE FOR VALUES IN (2) WITH (FILLFACTOR=90);
ALTER TABLE SESSION_STORAGE_P0 CLUSTER ON SESSION_STORAGE_P0_pkey;
ALTER TABLE SESSION_STORAGE_P1 CLUSTER ON SESSION_STORAGE_P1_pkey;
ALTER TABLE SESSION_STORAGE_P2 CLUSTER ON SESSION_STORAGE_P2_pkey;
CREATE TABLE IF NOT EXISTS RX_STREAM
(
    TENANT_ID                   TEXT        NOT NULL,
    RX_STREAM_ID                TEXT        NOT NULL,
    STREAM_ID                   TEXT        NOT NULL,
    ISSUER                      TEXT        NOT NULL,
    AUDIENCE                    TEXT        NOT NULL,
    EVENTS_SUPPORTED            TEXT,
    EVENTS_REQUESTED            TEXT        NOT NULL,
    EVENTS_DELIVERED            TEXT        NOT NULL,
    DELIVERY_METHOD             TEXT        NOT NULL,
    DELIVERY_ENDPOINT_URL       TEXT,
    MIN_VERIFICATION_INTERVAL   INTEGER     NOT NULL,
    DESCRIPTION                 TEXT,
    META_DATA_URL               TEXT        NOT NULL,
    METADATA_URI_AUTH           BOOLEAN     NOT NULL,
    NAME                        TEXT        NOT NULL,
    STATUS                      TEXT        NOT NULL,
    STATUS_REASON               TEXT,
    TYPE                        TEXT        NOT NULL,
    SUBJECT_NORMALIZATION       TEXT        NOT NULL,
    AUTH_SCHEME                 TEXT        NOT NULL,
    MAX_EVENTS                  INTEGER     NOT NULL,
    POLL_INTERVAL_SEC           INTEGER     NOT NULL,
    RETURN_IMMEDIATELY          BOOLEAN     NOT NULL,
    ROUTING_MODE                TEXT,
    ROUTING_EVENT_PROPERTY_NAME TEXT,
    CREATED_AT                  TIMESTAMPTZ NOT NULL,
    UPDATED_AT                  TIMESTAMPTZ NOT NULL,
    CONSTRAINT PK_RX_STREAM PRIMARY KEY (TENANT_ID, RX_STREAM_ID)
    ) WITH (FILLFACTOR=90);
CREATE INDEX IF NOT EXISTS RX_STREAM_IDX_TID_CREATED ON RX_STREAM (TENANT_ID, CREATED_AT DESC);
ALTER TABLE RX_STREAM CLUSTER ON PK_RX_STREAM;
CREATE TABLE IF NOT EXISTS RX_STREAM_POLL
(
    TENANT_ID      TEXT        NOT NULL,
    RX_STREAM_ID   TEXT        NOT NULL,
    NEXT_POLL_TIME TIMESTAMPTZ NOT NULL,
    CONSTRAINT PK_RX_STREAM_POLL PRIMARY KEY (TENANT_ID, RX_STREAM_ID)
    ) WITH (FILLFACTOR=70);
CREATE INDEX IF NOT EXISTS RX_STREAM_POLL_IDX_NPT ON RX_STREAM_POLL (NEXT_POLL_TIME ASC);
ALTER TABLE RX_STREAM_POLL CLUSTER ON RX_STREAM_POLL_IDX_NPT;
CREATE TABLE IF NOT EXISTS TX_STREAM
(
    TENANT_ID             TEXT        NOT NULL,
    OWNER_ID              TEXT        NOT NULL,
    STREAM_ID             TEXT        NOT NULL,
    DESCRIPTION           TEXT,
    AUDIENCE              TEXT        NOT NULL,
    EVENTS_REQUESTED      TEXT        NOT NULL,
    DELIVERY_METHOD       TEXT        NOT NULL,
    DELIVERY_ENDPOINT_URL TEXT,
    DELIVERY_AUTH_HEADER  TEXT,
    STATUS                TEXT,
    STATUS_REASON         TEXT,
    SIGNING_KEY_LABEL     TEXT,
    LAST_ACTIVITY_AT      TIMESTAMPTZ,
    CREATED_AT            TIMESTAMPTZ NOT NULL,
    UPDATED_AT            TIMESTAMPTZ NOT NULL,
    CONSTRAINT PK_TX_STREAM PRIMARY KEY (TENANT_ID, STREAM_ID)
    ) WITH (FILLFACTOR=90);
CREATE INDEX IF NOT EXISTS TX_STREAM_IDX_TID_OID ON TX_STREAM (TENANT_ID, OWNER_ID);
ALTER TABLE TX_STREAM CLUSTER ON PK_TX_STREAM;
CREATE TABLE IF NOT EXISTS TX_STREAM_PUSH
(
    TENANT_ID TEXT        NOT NULL,
    STREAM_ID TEXT        NOT NULL,
    ADDED_AT  TIMESTAMPTZ NOT NULL,
    CONSTRAINT PK_TX_STREAM_PUSH PRIMARY KEY (TENANT_ID, STREAM_ID)
    ) WITH (FILLFACTOR=100);
CREATE INDEX IF NOT EXISTS TX_STREAM_PUSH_IDX_ADDED ON TX_STREAM_PUSH (ADDED_AT ASC);
ALTER TABLE TX_STREAM_PUSH CLUSTER ON TX_STREAM_PUSH_IDX_ADDED;
CREATE TABLE IF NOT EXISTS EVENT_STREAM
(
    TENANT_ID  TEXT NOT NULL,
    EVENT_TYPE TEXT NOT NULL,
    STREAM_ID  TEXT NOT NULL,
    CONSTRAINT PK_EVENT_STREAM PRIMARY KEY (TENANT_ID, EVENT_TYPE, STREAM_ID)
    ) WITH (FILLFACTOR=100);
CREATE INDEX IF NOT EXISTS EVENT_STREAM_IDX_TIDSID ON EVENT_STREAM (TENANT_ID, STREAM_ID);
ALTER TABLE EVENT_STREAM CLUSTER ON PK_EVENT_STREAM;
CREATE TABLE IF NOT EXISTS SET_EVENT
(
    TENANT_ID              TEXT        NOT NULL,
    STREAM_ID              TEXT        NOT NULL,
    ID                     TEXT        NOT NULL,
    EPOCH_DAY_PARTITION_ID INTEGER     NOT NULL,
    OWNER_ID               TEXT        NOT NULL,
    SET                    TEXT,
    FORCE_TRANSMIT         BOOLEAN,
    CREATED_AT             TIMESTAMPTZ NOT NULL,
    CONSTRAINT PK_SET_EVENT PRIMARY KEY (TENANT_ID, STREAM_ID, ID, EPOCH_DAY_PARTITION_ID)
    ) PARTITION BY LIST (EPOCH_DAY_PARTITION_ID);
CREATE TABLE IF NOT EXISTS SET_EVENT_P0 PARTITION OF SET_EVENT FOR VALUES IN (0) WITH (FILLFACTOR=100);
CREATE TABLE IF NOT EXISTS SET_EVENT_P1 PARTITION OF SET_EVENT FOR VALUES IN (1) WITH (FILLFACTOR=100);
CREATE TABLE IF NOT EXISTS SET_EVENT_P2 PARTITION OF SET_EVENT FOR VALUES IN (2) WITH (FILLFACTOR=100);
ALTER TABLE SET_EVENT_P0 CLUSTER ON SET_EVENT_P0_pkey;
ALTER TABLE SET_EVENT_P1 CLUSTER ON SET_EVENT_P1_pkey;
ALTER TABLE SET_EVENT_P2 CLUSTER ON SET_EVENT_P2_pkey;
CREATE TABLE IF NOT EXISTS TX_SUBJECT
(
    TENANT_ID          TEXT        NOT NULL,
    STREAM_ID          TEXT        NOT NULL,
    SIGNATURE          TEXT        NOT NULL,
    SUBJECT_PROPERTIES TEXT        NOT NULL,
    VERIFIED           BOOLEAN,
    ACTION             TEXT        NOT NULL,
    CREATED_AT         TIMESTAMPTZ NOT NULL,
    UPDATED_AT         TIMESTAMPTZ NOT NULL,
    CONSTRAINT PK_TX_SUBJECT PRIMARY KEY (TENANT_ID, STREAM_ID, SIGNATURE)
    ) WITH (FILLFACTOR=90);
ALTER TABLE TX_SUBJECT CLUSTER ON PK_TX_SUBJECT;
CREATE TABLE IF NOT EXISTS HEART_BEAT
(
    ID                TEXT        NOT NULL,
    TYPE              TEXT        NOT NULL,
    HEART_BEAT_EXPIRY TIMESTAMPTZ NOT NULL,
    CONSTRAINT PK_HEART_BEAT PRIMARY KEY (ID, TYPE)
    ) WITH (FILLFACTOR=70);
CREATE INDEX IF NOT EXISTS HEART_BEAT_IDX_TYPEXP_ID ON HEART_BEAT (TYPE, HEART_BEAT_EXPIRY, ID ASC);
ALTER TABLE HEART_BEAT CLUSTER ON HEART_BEAT_IDX_TYPEXP_ID;