# Allow trusted (no-pw) access only from the host itself
local     all all               trust

# Allow authenticated access from localhost
host      all all 127.0.0.1/32  scram-sha-256
host      all all ::1/128       scram-sha-256

# Allow authenticated remote access via SSL only
hostssl   all all 0.0.0.0/0     scram-sha-256
hostnossl all all 0.0.0.0/0     reject