---
version: 1.0.0
logging:
  level: info

receiver:
  server: # HTTP server.
    ssl: # SSL cert / key for HTTPS
      key: "ks:server/key"
      certificate: "ks:server/cert"
  base_url: "https://receiver.dune.com:9043"

  management:
    enabled: true

  runtime:
    enabled: true

    # The number of worker threads processing the received events.
    worker_threads: 10

    # clean events periodically
    cleaner_interval_in_secs: 60
    event_states_to_clean:
      - "actioned"
      - "errored"

    action_rules:
      - event_type: "https://schemas.openid.net/secevent/caep/event-type/session-revoked"
        type: javascript
        content: "@js/log_event.js"
      - event_type: "https://schemas.openid.net/secevent/caep/event-type/device-compliance-change"
        type: javascript
        content: "@js/log_event.js"
      - event_type: "https://iam.ibm.com/secevent/ssf/event-type/application"
        type: javascript
        content: "@js/log_event.js"

# js engine configuration
javascript:
  timeout: 10
  max_concurrent_jobs: 16
  max_ctx_pre_isolate: 50